import { ThemeProvider } from '@/app/contexts/ThemeContex';
import { AuthProvider } from '@/app/contexts/AuthContext';
import Footer from '@/app/components/Footer';
import Header from '@/app/components/Header';
import Contents from './inicio/content';

import '@/app/styles/global.scss';
import '@/app/styles/theme.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children, contents }) {
  return (
    <html lang="en">
      <body className="root-layout">
        <AuthProvider>
          <ThemeProvider>
            <Header />
            <main>
            {children}
            </main>
            <Contents />
            <Footer />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
